
services:
  backend-app-dev:
    container_name: backend-app-dev
    depends_on:
      ldap-dev:
        condition: service_started
      postgres-dev:
        condition: service_started
    env_file:
      - .env.dev
    image: manumarcos/arreglaya-backend:dev
    ports:
      - "8081:8081"
    restart: unless-stopped

  ldap-dev:
    image: osixia/openldap:1.5.0
    env_file:
      - .env.dev
    ports:
      - "389:389"
      - "636:636"
    restart: unless-stopped
    volumes:
      - ldap_data_dev:/var/lib/ldap
      - slapd_data_dev:/etc/ldap/slapd.d
      - ./ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom

  postgres-dev:
    image: postgres:15-alpine
    env_file:
      - .env.dev
    ports:
      - "5433:5432"
    restart: unless-stopped
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  ldap_data_dev:
  slapd_data_dev:
  postgres_data_dev: