services:

  backend-app-prod:
    image: manumarcos/arreglaya-backend:latest
    container_name: backend-app-prod
    depends_on:
      - postgres-prod
      - ldap
    environment:
      - SERVER_PORT=${SERVER_PORT_PROD}
      - POSTGRES_DB=${POSTGRES_DB_PROD}
      - POSTGRES_USER=${POSTGRES_USER_PROD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_PROD}
      - LDAP_SERVER=${LDAP_SERVER}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_USER=cn=admin,${LDAP_BASE_DN}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - DATASOURCE_URL=${DATASOURCE_URL_PROD}
    ports:
      - "${SERVER_PORT_PROD}:${SERVER_PORT_PROD}"
    restart: unless-stopped

  backend-app-dev:
    image: manumarcos/arreglaya-backend:dev
    container_name: backend-app-dev
    depends_on:
      - postgres-dev
      - ldap
    environment:
      - SERVER_PORT=${SERVER_PORT_DEV}
      - POSTGRES_DB=${POSTGRES_DB_DEV}
      - POSTGRES_USER=${POSTGRES_USER_DEV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DEV}
      - LDAP_SERVER=${LDAP_SERVER}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_USER=cn=admin,${LDAP_BASE_DN}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - DATASOURCE_URL=${DATASOURCE_URL_DEV}
    ports:
      - "${SERVER_PORT_DEV}:${SERVER_PORT_DEV}"
    restart: unless-stopped


  postgres-prod:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB_PROD:-users_db}
      - POSTGRES_USER=${POSTGRES_USER_PROD:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_PROD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    hostname: postgres-prod

  postgres-dev:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB_DEV:-users_db}
      - POSTGRES_USER=${POSTGRES_USER_DEV:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DEV:-postgres}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    hostname: postgres-dev

  ldap:
    image: osixia/openldap:1.5.0
    restart: unless-stopped
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION=${LDAP_ORGANISATION:-ArreglaYa}
      - LDAP_DOMAIN=${LDAP_DOMAIN:-arreglaya.com}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD:-arreglayaadmin}
      - LDAP_PASSWORD_HASH={SHA}
    command: "--loglevel info --copy-service"
    volumes:
      - ldap:/var/lib/ldap
      - slapd:/etc/ldap/slapd.d
      - ./ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
    hostname: ldap

  ldap-account-manager:
    image: ghcr.io/ldapaccountmanager/lam:8.4
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - lamconfig:/var/lib/ldap-account-manager/config
    environment:
      - LAM_PASSWORD=${LAM_PASSWORD:-lamadmin}
      - LDAP_SERVER=ldap://ldap
      - LDAP_DOMAIN=${LDAP_DOMAIN:-arreglaya.com}
      - LDAP_USER=cn=admin,dc=arreglaya,dc=com
    depends_on:
      - ldap
    hostname: ldap-account-manager

volumes:
  postgres_data_prod:
  postgres_data_dev:
  lamconfig:
  ldap:
  slapd:
