services:
  # ENTORNO DE PRODUCCIÓN
  backend-app-prod:
    image: manumarcos/arreglaya-backend:latest
    container_name: backend-app-prod
    depends_on:
      - postgres-prod
      - ldap-prod
    environment:
      - SERVER_PORT=${SERVER_PORT_PROD}
      - POSTGRES_DB=${POSTGRES_DB_PROD}
      - POSTGRES_USER=${POSTGRES_USER_PROD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_PROD}
      - LDAP_SERVER=${LDAP_SERVER_PROD}
      - LDAP_DOMAIN=${LDAP_DOMAIN_PROD}
      - LDAP_BASE_DN=${LDAP_BASE_DN_PROD}
      - LDAP_USER=cn=admin,${LDAP_BASE_DN_PROD}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD_PROD}
      - DATASOURCE_URL=${DATASOURCE_URL_PROD}
    ports:
      - "${SERVER_PORT_PROD}:${SERVER_PORT_PROD}"
    restart: unless-stopped

  postgres-prod:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: postgres-prod
    environment:
      - POSTGRES_DB=${POSTGRES_DB_PROD}
      - POSTGRES_USER=${POSTGRES_USER_PROD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_PROD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  ldap-prod:
    image: osixia/openldap:1.5.0
    restart: unless-stopped
    ports:
      - "1389:389"
      - "1636:636"
    environment:
      - LDAP_ORGANISATION=${LDAP_ORGANISATION_PROD}
      - LDAP_DOMAIN=${LDAP_DOMAIN_PROD}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD_PROD}
    command: "--loglevel info --copy-service"
    volumes:
      - ldap_data_prod:/var/lib/ldap
      - slapd_data_prod:/etc/ldap/slapd.d
      - ./ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom

  # ENTORNO DE DESARROLLO
  backend-app-dev:
    image: manumarcos/arreglaya-backend:develop
    container_name: backend-app-dev
    depends_on:
      - postgres-dev
      - ldap-dev
    environment:
      - SERVER_PORT=${SERVER_PORT_DEV}
      - POSTGRES_DB=${POSTGRES_DB_DEV}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - LDAP_SERVER=${LDAP_SERVER_DEV}
      - LDAP_DOMAIN=${LDAP_DOMAIN_DEV}
      - LDAP_BASE_DN=${LDAP_BASE_DN_DEV}
      - LDAP_USER=cn=admin,${LDAP_BASE_DN_DEV}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD_DEV}
      - DATASOURCE_URL=${DATASOURCE_URL_DEV}
    ports:
      - "${SERVER_PORT_DEV}:${SERVER_PORT_DEV}"
    restart: unless-stopped

  postgres-dev:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: postgres-dev
    environment:
      - POSTGRES_DB=${POSTGRES_DB_DEV}
      - POSTGRES_USER=${POSTGRES_USER_DEV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DEV}
    ports:
      - "55432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  ldap-dev:
    image: osixia/openldap:1.5.0
    restart: unless-stopped
    ports:
      - "13890:389"
      - "16360:636"
    environment:
      - LDAP_ORGANISATION=${LDAP_ORGANISATION_DEV}
      - LDAP_DOMAIN=${LDAP_DOMAIN_DEV}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD_DEV}
    command: "--loglevel info --copy-service"
    volumes:
      - ldap_data_dev:/var/lib/ldap
      - slapd_data_dev:/etc/ldap/slapd.d
      - ./ldif-dev:/container/service/slapd/assets/config/bootstrap/ldif/custom

volumes:
  postgres_data_prod:
  ldap_data_prod:
  slapd_data_prod:
  postgres_data_dev:
  ldap_data_dev:
  slapd_data_dev:
