services:
  backend-app-prod:
    image: manumarcos/arreglaya-backend:latest
    container_name: backend-app-prod
    depends_on:
      - postgres-prod
      - ldap-prod
    environment:
      - SERVER_PORT=${SERVER_PORT_PROD}
      - POSTGRES_DB=${POSTGRES_DB_PROD}
      - POSTGRES_USER=${POSTGRES_USER_PROD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_PROD}
      - LDAP_SERVER=${LDAP_SERVER_PROD}
      - LDAP_DOMAIN=${LDAP_DOMAIN_PROD}
      - LDAP_BASE_DN=${LDAP_BASE_DN_PROD}
      - LDAP_USER=cn=admin,${LDAP_BASE_DN_PROD}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD_PROD}
      - DATASOURCE_URL=${DATASOURCE_URL_PROD}
    ports:
      - "${SERVER_PORT_PROD}:${SERVER_PORT_PROD}"
    restart: unless-stopped

  postgres-prod:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB_PROD}
      - POSTGRES_USER=${POSTGRES_USER_PROD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_PROD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  ldap-prod:
    image: osixia/openldap:1.5.0
    restart: unless-stopped
    ports:
      - "1389:389"
      - "1636:636"
    environment:
      - LDAP_ORGANISATION=${LDAP_ORGANISATION_PROD}
      - LDAP_DOMAIN=${LDAP_DOMAIN_PROD}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD_PROD}
    command: "--loglevel info --copy-service"
    volumes:
      - ldap_data_prod:/var/lib/ldap
      - slapd_data_prod:/etc/ldap/slapd.d
      - ./ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom

volumes:
  postgres_data_prod:
  ldap_data_prod:
  slapd_data_prod: